name: fetch-notion-data

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight
  workflow_dispatch:

jobs:
  fetch_notion_data:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install @notionhq/client

      - name: Fetch data from Notion
        id: notion_data
        run: |
          export NOTION_API_KEY='${{ secrets.NOTION_API_KEY }}'
          export NOTION_HABITS_DATABASE_ID='${{ vars.NOTION_HABITS_DATABASE_ID }}'

          node fetch_data.js

      - name: Save data to file
        uses: DamianReeves/write-file-action@master
        with:
          path: data.json
          write-mode: overwrite
          contents: ${{ steps.notion_data.outputs.data }}

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Update data.json from Notion'
          file_pattern: 'data.json'
